# Generated by Django 5.2 on 2026-04-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_term_status'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='class_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_requests', to='academics.class'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='department',
            field=models.CharField(blank=True, help_text='Legacy field - use class_fk instead', max_length=100),
        ),
    ]
