# Generated by Django 5.2 on 2026-05-01 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_resourcerequest_class_fk_and_more'),
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalresource',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_resources', to='users.branch'),
        ),
    ]
