# Generated by Django 5.2 on 2026-05-01 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_term_status'),
        ('materials', '0003_alter_digitalresource_branch'),
        ('students', '0002_initial'),
        ('teachers', '0010_evaluationperiodhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalResourceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('teachers', 'Teachers Only'), ('specific_students', 'Specific Students'), ('specific_teachers', 'Specific Teachers'), ('classes', 'Specific Classes')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='academics.class')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='materials.digitalresource')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='teachers.teacher')),
            ],
            options={
                'db_table': 'digital_resource_assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
