# Generated by Django 5.2 on 2026-05-02 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_term_status'),
        ('materials', '0004_digitalresourceassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalresource',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject this resource is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_resources', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='digitalresourceassignment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='academics.section'),
        ),
        migrations.AddField(
            model_name='digitalresourceassignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='academics.subject'),
        ),
    ]
