# Generated by Django 5.2 on 2026-04-09 20:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('subject_specialties', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('attendance_percentage', models.FloatField(blank=True, default=100.0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='users.branch')),
                ('class_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teachers', to='academics.class')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teachers', to='academics.section')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='academics.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_on', models.DateField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=True, help_text='Is this the primary teacher for this subject/section')),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacher')),
            ],
            options={
                'db_table': 'teacher_assignments',
                'unique_together': {('teacher', 'class_fk', 'section', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TeacherMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='First day of the month')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of days present', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_working_days', models.PositiveIntegerField(default=0)),
                ('days_present', models.PositiveIntegerField(default=0)),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('task_completion_rate', models.DecimalField(decimal_places=2, help_text='Percentage of tasks completed on time', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_tasks_assigned', models.PositiveIntegerField(default=0)),
                ('total_tasks_completed', models.PositiveIntegerField(default=0)),
                ('tasks_overdue', models.PositiveIntegerField(default=0)),
                ('lesson_coverage_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of planned lessons covered', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lessons_planned', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average rating for the month', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_ratings_received', models.PositiveIntegerField(default=0)),
                ('average_student_performance', models.DecimalField(blank=True, decimal_places=2, help_text='Average performance of students taught', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['teacher', 'month'], name='teachers_te_teacher_ed0b89_idx')],
                'unique_together': {('teacher', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TeacherPerformanceRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('category', models.CharField(choices=[('teaching_quality', 'Teaching Quality'), ('punctuality', 'Punctuality'), ('communication', 'Communication'), ('classroom_management', 'Classroom Management'), ('student_engagement', 'Student Engagement'), ('professionalism', 'Professionalism'), ('collaboration', 'Collaboration'), ('innovation', 'Innovation')], max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_ratings', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-rating_date'],
                'indexes': [models.Index(fields=['teacher', 'rating_date'], name='teachers_te_teacher_53f61c_idx'), models.Index(fields=['category'], name='teachers_te_categor_1437e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherPerformanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semester', 'Semester'), ('annual', 'Annual')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Overall performance score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ranking', models.PositiveIntegerField(blank=True, help_text='Ranking among all teachers', null=True)),
                ('total_teachers', models.PositiveIntegerField(blank=True, help_text='Total number of teachers in ranking', null=True)),
                ('strengths', models.TextField(blank=True, help_text='Key strengths identified')),
                ('areas_for_improvement', models.TextField(blank=True, help_text='Areas needing improvement')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for growth')),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('task_completion_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lesson_coverage_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('student_performance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['teacher', 'report_period'], name='teachers_te_teacher_9133ef_idx'), models.Index(fields=['start_date', 'end_date'], name='teachers_te_start_d_ae97b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('lesson_plan', 'Lesson Planning'), ('grading', 'Grading'), ('meeting', 'Meeting'), ('parent_communication', 'Parent Communication'), ('professional_development', 'Professional Development'), ('administrative', 'Administrative'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['teacher', 'date'], name='teachers_te_teacher_c9de50_idx'), models.Index(fields=['status'], name='teachers_te_status_c28e0c_idx')],
            },
        ),
    ]
