# Generated by Django 5.2 on 2026-04-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_term_branch_alter_term_academic_year_alter_term_name_and_more'),
        ('teachers', '0002_teacherassignment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.term'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Leave blank to assign teacher to ALL sections of this class', null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.section'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'class_fk', 'section', 'subject', 'term')},
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['term', 'is_active'], name='teacher_ass_term_id_c550c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('class_fk', 'section', 'subject', 'term'), name='unique_primary_teacher_per_class_section_subject_term'),
        ),
    ]
