# Generated by Django 5.2 on 2026-04-20 08:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_term_status'),
        ('teachers', '0003_alter_teacherassignment_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMeasurementCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Criteria name (e.g., Teaching Quality, Punctuality)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this criteria measures')),
                ('code', models.CharField(help_text='Unique code for this criteria (e.g., teaching_quality)', max_length=50, unique=True)),
                ('measurement_type', models.CharField(choices=[('rating_1_5', 'Rating Scale (1-5)'), ('rating_1_10', 'Rating Scale (1-10)'), ('percentage', 'Percentage (0-100)'), ('boolean', 'Yes/No'), ('text', 'Text/Comment'), ('numeric', 'Numeric Value')], default='rating_1_5', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight for this criteria in overall calculation (default 1.0)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this criteria is currently active')),
                ('is_default', models.BooleanField(default=False, help_text='System default criteria that cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'performance measurement criteria',
                'db_table': 'performance_measurement_criteria',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPerformanceEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='e.g., 2025-2026', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated overall performance score', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weighted_average', models.DecimalField(blank=True, decimal_places=2, help_text='Weighted average of all rating criteria', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('strengths', models.TextField(blank=True, help_text='Key strengths identified')),
                ('areas_for_improvement', models.TextField(blank=True, help_text='Areas needing improvement')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for professional development')),
                ('action_items', models.TextField(blank=True, help_text='Specific action items for the teacher')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_approved', to=settings.AUTH_USER_MODEL)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_reviewed', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to='teachers.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_evaluations', to='academics.term')),
            ],
            options={
                'db_table': 'teacher_performance_evaluations',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPerformanceEvaluationRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_value', models.DecimalField(blank=True, decimal_places=2, help_text='The actual rating value (1-5, 1-10, percentage, etc.)', max_digits=8, null=True)),
                ('text_value', models.TextField(blank=True, help_text='For text/comment type criteria')),
                ('boolean_value', models.BooleanField(blank=True, help_text='For yes/no type criteria', null=True)),
                ('normalized_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score normalized to 0-5 scale for aggregation', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Specific comment for this criteria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_ratings', to='teachers.performancemeasurementcriteria')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_ratings', to='teachers.teacherperformanceevaluation')),
                ('rated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria_ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_performance_evaluation_ratings',
                'ordering': ['criteria__name'],
            },
        ),
        migrations.AddIndex(
            model_name='performancemeasurementcriteria',
            index=models.Index(fields=['is_active', 'is_default'], name='performance_is_acti_db9e21_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemeasurementcriteria',
            index=models.Index(fields=['code'], name='performance_code_fa1cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherperformanceevaluation',
            index=models.Index(fields=['teacher', 'term'], name='teacher_per_teacher_26c46e_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherperformanceevaluation',
            index=models.Index(fields=['status'], name='teacher_per_status_e8ac3f_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherperformanceevaluation',
            index=models.Index(fields=['academic_year'], name='teacher_per_academi_387345_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherperformanceevaluation',
            unique_together={('teacher', 'term')},
        ),
        migrations.AddIndex(
            model_name='teacherperformanceevaluationrating',
            index=models.Index(fields=['evaluation', 'criteria'], name='teacher_per_evaluat_9549a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherperformanceevaluationrating',
            unique_together={('evaluation', 'criteria')},
        ),
    ]
