# Generated by Django 5.2 on 2026-04-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_add_evaluation_period_settings_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherperformancerating',
            name='category',
            field=models.CharField(help_text='Criteria code matching PerformanceMeasurementCriteria.code (e.g., teaching_quality, how_to_teach2)', max_length=50),
        ),
    ]
