# Generated by Django 5.2 on 2026-04-29 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_teacherperformancerating_evaluation_period_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationPeriodHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_id', models.CharField(help_text='Unique identifier for this period', max_length=100, unique=True)),
                ('period_number', models.IntegerField(default=1, help_text='Sequential period number (1, 2, 3, etc.)')),
                ('is_open', models.BooleanField(default=False, help_text='Is this period currently open')),
                ('opened_at', models.DateTimeField(blank=True, help_text='When this period was opened', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When this period was closed', null=True)),
                ('name', models.CharField(blank=True, help_text="Period name/label (e.g., 'Term 1 2026')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this evaluation period')),
                ('total_ratings', models.IntegerField(default=0, help_text='Total ratings during this period')),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluation_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Evaluation Period Histories',
                'db_table': 'teacher_evaluation_period_history',
                'ordering': ['-period_number'],
            },
        ),
    ]
