# Generated by Django 5.2 on 2026-04-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='users.branch'),
        ),
        migrations.AlterField(
            model_name='term',
            name='academic_year',
            field=models.CharField(help_text='e.g., 2025-2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Summer', 'Summer'), ('Winter', 'Winter')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('branch', 'academic_year', 'name')},
        ),
    ]
