# Generated by Django 5.2 on 2026-04-11 15:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_term_branch_alter_term_academic_year_alter_term_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Subject name (e.g., Math, English, Physics)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the subject')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'global_subjects',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['grade']},
        ),
        migrations.AlterModelOptions(
            name='classsubject',
            options={'ordering': ['class_fk__grade', 'global_subject__name']},
        ),
        migrations.AddField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='book_code',
            field=models.CharField(blank=True, help_text='Book code or ISBN for this subject', max_length=50),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject_code',
            field=models.CharField(blank=True, help_text='Custom subject code for this class (e.g., MTH-09, ENG-10)', max_length=20),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='syllabus',
            field=models.TextField(blank=True, help_text='Content, topics, or syllabus for this class'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.CharField(help_text='Class grade (e.g., Grade 9, Grade 10)', max_length=20),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classes', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='global_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academics.globalsubject'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_fk', 'global_subject')},
        ),
    ]
