# Generated by Django 5.2 on 2026-04-12 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_globalsubject_alter_class_options_and_more'),
        ('teachers', '0003_alter_teacherassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sections', to='teachers.teacher'),
        ),
    ]
