# Generated by Django 5.2 on 2026-04-12 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_section_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='global_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.globalsubject'),
        ),
    ]
