# Generated by Django 5.2 on 2026-04-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_subject_global_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('current', 'Current'), ('closed', 'Closed')], default='upcoming', max_length=20),
        ),
    ]
