# Generated by Django 5.2 on 2026-04-09 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schedule', '0001_initial'),
        ('students', '0002_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObjectives',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('framework_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assigned_date', models.DateField()),
                ('due_date', models.DateField()),
                ('file_url', models.URLField(blank=True, null=True)),
                ('is_group_assignment', models.BooleanField(default=False)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('class_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academics.section')),
                ('students', models.ManyToManyField(blank=True, related_name='assignments', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_score', models.FloatField()),
                ('score', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlans',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('lesson_aims', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans_by_class', to='academics.class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherassignment')),
                ('learner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans_by_group', to='academics.class')),
                ('learning_objectives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessontopics.learningobjectives')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanEvaluations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_plan_evaluation', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessontopics.lessonplans')),
            ],
        ),
        migrations.CreateModel(
            name='LessonActivities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('time_slot', models.CharField(max_length=50)),
                ('topic_content', models.TextField()),
                ('learner_activity', models.TextField()),
                ('formative_assessment', models.TextField()),
                ('materials', models.TextField()),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessontopics.lessonplans')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveSubunits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lessonplans',
            name='subunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessontopics.objectivesubunits'),
        ),
        migrations.AddField(
            model_name='learningobjectives',
            name='subunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessontopics.objectivesubunits'),
        ),
        migrations.CreateModel(
            name='ObjectiveUnits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessontopics.objectivecategories')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='objectivesubunits',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessontopics.objectiveunits'),
        ),
        migrations.AddField(
            model_name='lessonplans',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='lessontopics.objectiveunits'),
        ),
        migrations.AddField(
            model_name='learningobjectives',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessontopics.objectiveunits'),
        ),
        migrations.CreateModel(
            name='StudentAssignments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_url', models.URLField(blank=True, null=True)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessontopics.assignments')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanObjectives',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('score_type', models.CharField(choices=[('star', 'star rating'), ('grade', 'Grade text'), ('percent', 'Percentage')], default='numeric', max_length=20)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessontopics.learningobjectives')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='students.student')),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessontopics.lessonplans')),
            ],
            options={
                'unique_together': {('lesson_plan', 'objective', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubunitProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessontopics.objectivesubunits')),
            ],
            options={
                'db_table': 'class_subunit_progress',
                'unique_together': {('class_fk', 'section', 'subject', 'subunit')},
            },
        ),
        migrations.CreateModel(
            name='ClassUnitProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessontopics.objectiveunits')),
            ],
            options={
                'db_table': 'class_unit_progress',
                'unique_together': {('class_fk', 'section', 'subject', 'unit')},
            },
        ),
    ]
