# Generated by Django 5.2 on 2026-04-10 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('lessontopics', '0001_initial'),
        ('schedule', '0001_initial'),
        ('students', '0002_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.PositiveIntegerField(help_text='Order in which unit is taught')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum_mappings',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('overall_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank_in_class', models.PositiveIntegerField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_remarks', models.TextField(blank=True)),
                ('principal_remarks', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_cards',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_score', models.FloatField(blank=True, null=True)),
                ('exam_max_score', models.FloatField(default=100)),
                ('assignment_avg', models.FloatField(blank=True, null=True)),
                ('assignment_max', models.FloatField(default=100)),
                ('attendance_score', models.FloatField(blank=True, null=True)),
                ('attendance_max', models.FloatField(default=100)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('total_max', models.FloatField(default=100)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descriptive_grade', models.CharField(blank=True, choices=[('EX', 'Excellent - Outstanding performance'), ('VG', 'Very Good - Above average performance'), ('G', 'Good - Satisfactory performance'), ('S', 'Satisfactory - Meets expectations'), ('NI', 'Needs Improvement - Below expectations'), ('U', 'Unsatisfactory - Fails to meet requirements')], help_text='For grades 1-8', max_length=2, null=True)),
                ('letter_grade', models.CharField(blank=True, choices=[('A', 'A - Excellent (90-100%)'), ('B', 'B - Good (80-89%)'), ('C', 'C - Satisfactory (70-79%)'), ('D', 'D - Passing (60-69%)'), ('E', 'E - Needs Improvement (50-59%)'), ('F', 'F - Fail (Below 50%)')], help_text='For grades 9-12', max_length=1, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'report_card_subjects',
            },
        ),
        migrations.AddField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='max_score',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='assignments',
            name='teacher_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherassignment'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='classunitprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examresults',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='examresults',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='examresults',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='examresults',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_exam_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresults',
            name='teacher_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherassignment'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='max_score',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='assignments',
            index=models.Index(fields=['teacher_assignment', 'assigned_date'], name='assignments_teacher_da87a3_idx'),
        ),
        migrations.AddIndex(
            model_name='assignments',
            index=models.Index(fields=['class_fk', 'section', 'due_date'], name='assignments_class_f_c8d6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='classunitprogress',
            index=models.Index(fields=['class_fk', 'subject', 'is_current'], name='class_unit__class_f_67aa33_idx'),
        ),
        migrations.AddIndex(
            model_name='classunitprogress',
            index=models.Index(fields=['class_fk', 'section', 'subject'], name='class_unit__class_f_9c467f_idx'),
        ),
        migrations.AddIndex(
            model_name='examresults',
            index=models.Index(fields=['student', 'teacher_assignment'], name='exam_result_student_fe8a36_idx'),
        ),
        migrations.AddIndex(
            model_name='examresults',
            index=models.Index(fields=['exam', 'teacher_assignment'], name='exam_result_exam_id_2b5dad_idx'),
        ),
        migrations.AlterModelTable(
            name='assignments',
            table='assignments',
        ),
        migrations.AlterModelTable(
            name='examresults',
            table='exam_results',
        ),
        migrations.AddField(
            model_name='curriculummapping',
            name='class_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class'),
        ),
        migrations.AddField(
            model_name='curriculummapping',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='curriculummapping',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.AddField(
            model_name='curriculummapping',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessontopics.objectiveunits'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='class_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.student'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.AddField(
            model_name='reportcardsubject',
            name='report_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='lessontopics.reportcard'),
        ),
        migrations.AddField(
            model_name='reportcardsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='reportcardsubject',
            name='teacher_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculummapping',
            unique_together={('class_fk', 'subject', 'unit')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcardsubject',
            unique_together={('report_card', 'teacher_assignment')},
        ),
    ]
