# Generated by Django 5.2 on 2026-04-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessontopics', '0002_curriculummapping_reportcard_reportcardsubject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplans',
            name='learning_objectives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessontopics.learningobjectives'),
        ),
    ]
