# Generated by Django 5.2 on 2026-04-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessontopics', '0003_alter_lessonplans_learning_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplans',
            name='block',
            field=models.CharField(blank=True, help_text='e.g., Morning Block, Afternoon Block', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lessonplans',
            name='week',
            field=models.IntegerField(blank=True, help_text='Week number in the term', null=True),
        ),
    ]
