# Generated by Django 5.2 on 2026-04-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessontopics', '0004_lessonplans_block_lessonplans_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubunitprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
