# Generated by Django 5.2 on 2026-04-21 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_term_status'),
        ('lessontopics', '0005_classsubunitprogress_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplanevaluations',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.section'),
        ),
    ]
