# Generated by Django 5.2 on 2026-04-24 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_term_status'),
        ('lessontopics', '0006_alter_lessonplanevaluations_section'),
        ('students', '0002_initial'),
        ('teachers', '0006_add_evaluation_period_settings_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ca_type', models.CharField(choices=[('quiz', 'Daily Quiz'), ('homework', 'Homework'), ('participation', 'Class Participation'), ('classwork', 'Classwork'), ('project', 'Mini Project'), ('assignment', 'Assignment')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(default=100)),
                ('weight', models.FloatField(default=1.0)),
                ('date_given', models.DateField()),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherassignment')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
            options={
                'db_table': 'continuous_assessments',
            },
        ),
        migrations.CreateModel(
            name='SkillsAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(choices=[('communication', 'Communication Skills'), ('teamwork', 'Teamwork & Collaboration'), ('critical_thinking', 'Critical Thinking'), ('creativity', 'Creativity & Innovation'), ('leadership', 'Leadership'), ('discipline', 'Discipline & Punctuality'), ('participation', 'Active Participation'), ('homework_completion', 'Homework Completion'), ('respect', 'Respect for Others'), ('self_confidence', 'Self-Confidence')], max_length=30)),
                ('rating', models.CharField(choices=[('EX', 'Excellent'), ('VG', 'Very Good'), ('G', 'Good'), ('S', 'Satisfactory'), ('NI', 'Needs Improvement'), ('U', 'Unsatisfactory')], max_length=2)),
                ('comment', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherassignment')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
            options={
                'db_table': 'skills_assessments',
                'unique_together': {('student', 'teacher_assignment', 'term', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='StudentRank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.FloatField()),
                ('total_max', models.FloatField()),
                ('percentage', models.FloatField()),
                ('position', models.PositiveIntegerField()),
                ('total_students', models.PositiveIntegerField()),
                ('out_of', models.CharField(max_length=20)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
            options={
                'db_table': 'student_ranks',
                'ordering': ['class_fk', 'section', 'term', 'position'],
                'unique_together': {('student', 'class_fk', 'section', 'term')},
            },
        ),
        migrations.CreateModel(
            name='TeacherComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherassignment')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
            options={
                'db_table': 'teacher_comments',
                'unique_together': {('student', 'teacher_assignment', 'term')},
            },
        ),
    ]
