# Generated by Django 5.2 on 2026-04-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessontopics', '0007_continuousassessment_skillsassessment_studentrank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcardsubject',
            name='ca_max',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='reportcardsubject',
            name='ca_score',
            field=models.FloatField(blank=True, help_text='Weighted average of all CA items', null=True),
        ),
    ]
