# Generated by Django 5.2 on 2026-04-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessontopics', '0008_reportcardsubject_ca_max_reportcardsubject_ca_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcardsubject',
            name='assignment_weight',
            field=models.FloatField(default=10, help_text='Custom weight for assignments (default 10%)'),
        ),
        migrations.AddField(
            model_name='reportcardsubject',
            name='attendance_weight',
            field=models.FloatField(default=10, help_text='Custom weight for attendance (default 10%)'),
        ),
        migrations.AddField(
            model_name='reportcardsubject',
            name='ca_weight',
            field=models.FloatField(default=20, help_text='Custom weight for continuous assessment (default 20%)'),
        ),
        migrations.AddField(
            model_name='reportcardsubject',
            name='exam_weight',
            field=models.FloatField(default=60, help_text='Custom weight for exam (default 60%)'),
        ),
        migrations.AlterField(
            model_name='reportcardsubject',
            name='assignment_max',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='reportcardsubject',
            name='attendance_max',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='reportcardsubject',
            name='exam_max_score',
            field=models.FloatField(default=5),
        ),
    ]
