# Generated by Django 5.2 on 2026-04-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessontopics', '0009_reportcardsubject_assignment_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplans',
            name='lesson_date',
            field=models.DateField(blank=True, help_text='Date when the lesson is scheduled/completed', null=True),
        ),
    ]
