/**
 * Role-Based Access Control Configuration
 * Based on School Management System Requirements
 */

export const ROLES = {
  STUDENT: 'student',
  PARENT: 'parent',
  TEACHER: 'teacher',
  ADMIN: 'admin',
  STAFF: 'staff',
  HR: 'hr',
  COUNSELOR: 'counselor',
  CLINIC: 'clinic',
  TLH: 'tlh', // Teaching Learning Head
  ANALYST: 'analyst',
  FINANCE: 'finance',
  COMMUNICATION: 'communication',
  CEO: 'ceo',
  SUPER_ADMIN: 'super_admin',
  LIBRARIAN: 'librarian'
};

export const PERMISSIONS = {
  // Dashboard Access
  VIEW_DASHBOARD: 'view_dashboard',

  // Student Management
  VIEW_STUDENTS: 'view_students',
  CREATE_STUDENT: 'create_student',
  EDIT_STUDENT: 'edit_student',
  DELETE_STUDENT: 'delete_student',
  UPLOAD_STUDENTS: 'upload_students',
  VIEW_STUDENT_PROFILE: 'view_student_profile',
  VIEW_STUDENT_HEALTH: 'view_student_health',
  EDIT_STUDENT_HEALTH: 'edit_student_health',
  VIEW_STUDENT_BEHAVIOR: 'view_student_behavior',
  RATE_STUDENT_BEHAVIOR: 'rate_student_behavior',
  VIEW_STUDENT_ATTENDANCE: 'view_student_attendance',
  MARK_STUDENT_ATTENDANCE: 'mark_student_attendance',
  VIEW_STUDENT_GRADES: 'view_student_grades',
  EDIT_STUDENT_GRADES: 'edit_student_grades',
  GENERATE_STUDENT_REPORT: 'generate_student_report',

  // Teacher Management
  VIEW_TEACHERS: 'view_teachers',
  CREATE_TEACHER: 'create_teacher',
  EDIT_TEACHER: 'edit_teacher',
  DELETE_TEACHER: 'delete_teacher',
  UPLOAD_TEACHERS: 'upload_teachers',
  VIEW_TEACHER_PROFILE: 'view_teacher_profile',
  RATE_TEACHER: 'rate_teacher',
  VIEW_TEACHER_PERFORMANCE: 'view_teacher_performance',
  EVALUATE_TEACHER: 'evaluate_teacher',
  VIEW_TEACHER_RANKING: 'view_teacher_ranking',
  MANAGE_TEACHER_PERFORMANCE: 'manage_teacher_performance',

  // Parent Management
  VIEW_PARENTS: 'view_parents',
  CREATE_PARENT: 'create_parent',
  EDIT_PARENT: 'edit_parent',
  DELETE_PARENT: 'delete_parent',
  UPLOAD_PARENTS: 'upload_parents',

  // Class & Schedule Management
  VIEW_CLASSES: 'view_classes',
  CREATE_CLASS: 'create_class',
  EDIT_CLASS: 'edit_class',
  DELETE_CLASS: 'delete_class',
  VIEW_SCHEDULE: 'view_schedule',
  CREATE_SCHEDULE: 'create_schedule',
  EDIT_SCHEDULE: 'edit_schedule',
  IMPORT_SCHEDULE: 'import_schedule',

  // Subject Management
  VIEW_SUBJECTS: 'view_subjects',
  CREATE_SUBJECT: 'create_subject',
  EDIT_SUBJECT: 'edit_subject',
  DELETE_SUBJECT: 'delete_subject',

  // Assignment & Homework
  VIEW_ASSIGNMENTS: 'view_assignments',
  CREATE_ASSIGNMENT: 'create_assignment',
  EDIT_ASSIGNMENT: 'edit_assignment',
  DELETE_ASSIGNMENT: 'delete_assignment',
  SUBMIT_ASSIGNMENT: 'submit_assignment',
  GRADE_ASSIGNMENT: 'grade_assignment',

  // Lesson Planning
  VIEW_LESSON_PLANS: 'view_lesson_plans',
  CREATE_LESSON_PLAN: 'create_lesson_plan',
  EDIT_LESSON_PLAN: 'edit_lesson_plan',
  DELETE_LESSON_PLAN: 'delete_lesson_plan',
  EVALUATE_LESSON_PLAN: 'evaluate_lesson_plan',

  // Communication
  VIEW_ANNOUNCEMENTS: 'view_announcements',
  CREATE_ANNOUNCEMENT: 'create_announcement',
  EDIT_ANNOUNCEMENT: 'edit_announcement',
  DELETE_ANNOUNCEMENT: 'delete_announcement',
  SEND_URGENT_NOTICE: 'send_urgent_notice',
  CHAT_WITH_TEACHERS: 'chat_with_teachers',
  CHAT_WITH_PARENTS: 'chat_with_parents',
  CHAT_WITH_STUDENTS: 'chat_with_students',
  CHAT_WITH_ADMIN: 'chat_with_admin',
  CREATE_GROUP_CHAT: 'create_group_chat',
  REQUEST_MEETING: 'request_meeting',
  APPROVE_MEETING: 'approve_meeting',
  RATE_MEETING: 'rate_meeting',

  // Leave Management
  VIEW_LEAVE_REQUESTS: 'view_leave_requests',
  CREATE_LEAVE_REQUEST: 'create_leave_request',
  APPROVE_LEAVE_REQUEST: 'approve_leave_request',
  REJECT_LEAVE_REQUEST: 'reject_leave_request',

  // Task Management
  VIEW_TASKS: 'view_tasks',
  CREATE_TASK: 'create_task',
  EDIT_TASK: 'edit_task',
  DELETE_TASK: 'delete_task',
  ASSIGN_TASK: 'assign_task',
  COMPLETE_TASK: 'complete_task',

  // Resource Management
  VIEW_RESOURCES: 'view_resources',
  UPLOAD_RESOURCES: 'upload_resources',
  DELETE_RESOURCES: 'delete_resources',
  DOWNLOAD_RESOURCES: 'download_resources',

  // Inventory/Materials Management
  VIEW_INVENTORY: 'view_inventory',
  CREATE_INVENTORY: 'create_inventory',
  EDIT_INVENTORY: 'edit_inventory',
  REQUEST_MATERIALS: 'request_materials',
  APPROVE_MATERIAL_REQUEST: 'approve_material_request',
  VIEW_MATERIAL_REQUESTS: 'view_material_requests',
  REQUEST_PURCHASE: 'request_purchase',
  REQUEST_DUPLICATION: 'request_duplication',

  // Library Management
  VIEW_LIBRARY: 'view_library',
  MANAGE_LIBRARY: 'manage_library',
  BORROW_BOOK: 'borrow_book',
  RETURN_BOOK: 'return_book',

  // Finance
  VIEW_EXPENSES: 'view_expenses',
  VIEW_FINANCIAL_REPORTS: 'view_financial_reports',
  MANAGE_PAYMENTS: 'manage_payments',

  // Reports & Analytics
  VIEW_REPORTS: 'view_reports',
  GENERATE_REPORTS: 'generate_reports',
  EXPORT_DATA: 'export_data',
  VIEW_ANALYTICS: 'view_analytics',

  // Blog
  VIEW_BLOG: 'view_blog',
  CREATE_BLOG_POST: 'create_blog_post',
  EDIT_BLOG_POST: 'edit_blog_post',
  DELETE_BLOG_POST: 'delete_blog_post',

  // User Management
  VIEW_USERS: 'view_users',
  CREATE_USER: 'create_user',
  EDIT_USER: 'edit_user',
  DELETE_USER: 'delete_user',
  MANAGE_ROLES: 'manage_roles',

  // System Configuration
  SYSTEM_SETTINGS: 'system_settings',
  MANAGE_BRANCHES: 'manage_branches',
};

// Role Permission Mapping
export const ROLE_PERMISSIONS = {
  [ROLES.STUDENT]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STUDENT_PROFILE,
    PERMISSIONS.VIEW_SCHEDULE,
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.SUBMIT_ASSIGNMENT,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_RESOURCES,
    PERMISSIONS.DOWNLOAD_RESOURCES,
    PERMISSIONS.VIEW_BLOG,
    PERMISSIONS.VIEW_LIBRARY,
    PERMISSIONS.BORROW_BOOK,
    PERMISSIONS.RETURN_BOOK,
    PERMISSIONS.VIEW_LEAVE_REQUESTS,
    PERMISSIONS.CREATE_LEAVE_REQUEST,
  ],

  [ROLES.PARENT]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STUDENT_PROFILE,
    PERMISSIONS.VIEW_STUDENT_ATTENDANCE,
    PERMISSIONS.VIEW_STUDENT_GRADES,
    PERMISSIONS.VIEW_STUDENT_BEHAVIOR,
    PERMISSIONS.VIEW_STUDENT_HEALTH,
    PERMISSIONS.VIEW_SCHEDULE,
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.CHAT_WITH_TEACHERS,
    PERMISSIONS.CHAT_WITH_ADMIN,
    PERMISSIONS.REQUEST_MEETING,
    PERMISSIONS.RATE_MEETING,
    PERMISSIONS.RATE_TEACHER,
    PERMISSIONS.CREATE_LEAVE_REQUEST,
    PERMISSIONS.VIEW_RESOURCES,
    PERMISSIONS.DOWNLOAD_RESOURCES,
    PERMISSIONS.VIEW_BLOG,
    PERMISSIONS.GENERATE_STUDENT_REPORT,
  ],

  [ROLES.TEACHER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_TEACHER_PROFILE,
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.VIEW_STUDENT_PROFILE,
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.VIEW_SCHEDULE,
    PERMISSIONS.VIEW_STUDENT_ATTENDANCE,
    PERMISSIONS.MARK_STUDENT_ATTENDANCE,
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.CREATE_ASSIGNMENT,
    PERMISSIONS.EDIT_ASSIGNMENT,
    PERMISSIONS.DELETE_ASSIGNMENT,
    PERMISSIONS.GRADE_ASSIGNMENT,
    PERMISSIONS.VIEW_LESSON_PLANS,
    PERMISSIONS.CREATE_LESSON_PLAN,
    PERMISSIONS.EDIT_LESSON_PLAN,
    PERMISSIONS.VIEW_STUDENT_BEHAVIOR,
    PERMISSIONS.RATE_STUDENT_BEHAVIOR,
    PERMISSIONS.VIEW_STUDENT_GRADES,
    PERMISSIONS.EDIT_STUDENT_GRADES,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.CREATE_ANNOUNCEMENT,
    PERMISSIONS.CHAT_WITH_TEACHERS,
    PERMISSIONS.CHAT_WITH_STUDENTS,
    PERMISSIONS.CHAT_WITH_ADMIN,
    PERMISSIONS.REQUEST_MEETING,
    PERMISSIONS.RATE_MEETING,
    PERMISSIONS.VIEW_RESOURCES,
    PERMISSIONS.UPLOAD_RESOURCES,
    PERMISSIONS.DOWNLOAD_RESOURCES,
    PERMISSIONS.REQUEST_MATERIALS,
    PERMISSIONS.VIEW_MATERIAL_REQUESTS,
    PERMISSIONS.REQUEST_DUPLICATION,
    PERMISSIONS.VIEW_BLOG,
    PERMISSIONS.CREATE_BLOG_POST,
    PERMISSIONS.EDIT_BLOG_POST,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.COMPLETE_TASK,
    PERMISSIONS.VIEW_TEACHER_PERFORMANCE,
    PERMISSIONS.VIEW_TEACHER_RANKING,
    PERMISSIONS.GENERATE_STUDENT_REPORT,
    PERMISSIONS.CREATE_SCHEDULE,
    PERMISSIONS.EDIT_SCHEDULE,
  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.CREATE_STUDENT,
    PERMISSIONS.EDIT_STUDENT,
    PERMISSIONS.DELETE_STUDENT,
    PERMISSIONS.UPLOAD_STUDENTS,
    PERMISSIONS.VIEW_TEACHERS,
    PERMISSIONS.CREATE_TEACHER,
    PERMISSIONS.EDIT_TEACHER,
    PERMISSIONS.DELETE_TEACHER,
    PERMISSIONS.UPLOAD_TEACHERS,
    PERMISSIONS.VIEW_PARENTS,
    PERMISSIONS.CREATE_PARENT,
    PERMISSIONS.EDIT_PARENT,
    PERMISSIONS.DELETE_PARENT,
    PERMISSIONS.UPLOAD_PARENTS,
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.CREATE_CLASS,
    PERMISSIONS.EDIT_CLASS,
    PERMISSIONS.DELETE_CLASS,
    PERMISSIONS.VIEW_SCHEDULE,
    PERMISSIONS.CREATE_SCHEDULE,
    PERMISSIONS.EDIT_SCHEDULE,
    PERMISSIONS.IMPORT_SCHEDULE,
    PERMISSIONS.VIEW_SUBJECTS,
    PERMISSIONS.CREATE_SUBJECT,
    PERMISSIONS.EDIT_SUBJECT,
    PERMISSIONS.DELETE_SUBJECT,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.CREATE_ANNOUNCEMENT,
    PERMISSIONS.EDIT_ANNOUNCEMENT,
    PERMISSIONS.DELETE_ANNOUNCEMENT,
    PERMISSIONS.SEND_URGENT_NOTICE,
    PERMISSIONS.CREATE_GROUP_CHAT,
    PERMISSIONS.VIEW_LEAVE_REQUESTS,
    PERMISSIONS.APPROVE_LEAVE_REQUEST,
    PERMISSIONS.REJECT_LEAVE_REQUEST,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.CREATE_INVENTORY,
    PERMISSIONS.EDIT_INVENTORY,
    PERMISSIONS.VIEW_MATERIAL_REQUESTS,
    PERMISSIONS.APPROVE_MATERIAL_REQUEST,
    PERMISSIONS.VIEW_LIBRARY,
    PERMISSIONS.MANAGE_LIBRARY,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.VIEW_BLOG,
    PERMISSIONS.CREATE_BLOG_POST,
    PERMISSIONS.EDIT_BLOG_POST,
    PERMISSIONS.DELETE_BLOG_POST,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.DELETE_TASK,
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.VIEW_TEACHER_PERFORMANCE,
    PERMISSIONS.EVALUATE_TEACHER,
    PERMISSIONS.VIEW_TEACHER_RANKING,
    PERMISSIONS.MANAGE_TEACHER_PERFORMANCE,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.EDIT_USER,
    PERMISSIONS.DELETE_USER,
  ],

  [ROLES.LIBRARIAN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_LIBRARY,
    PERMISSIONS.MANAGE_LIBRARY,
    PERMISSIONS.BORROW_BOOK,
    PERMISSIONS.RETURN_BOOK,
    PERMISSIONS.VIEW_STUDENT_PROFILE,
    PERMISSIONS.VIEW_TEACHER_PROFILE,
  ],

  [ROLES.HR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_TEACHERS,
    PERMISSIONS.CREATE_TEACHER,
    PERMISSIONS.EDIT_TEACHER,
    PERMISSIONS.DELETE_TEACHER,
    PERMISSIONS.UPLOAD_TEACHERS,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.EDIT_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.VIEW_TEACHER_PERFORMANCE,
    PERMISSIONS.MANAGE_TEACHER_PERFORMANCE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_REPORTS,
  ],

  [ROLES.COUNSELOR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.VIEW_STUDENT_PROFILE,
    PERMISSIONS.VIEW_STUDENT_BEHAVIOR,
    PERMISSIONS.RATE_STUDENT_BEHAVIOR,
    PERMISSIONS.VIEW_STUDENT_HEALTH,
    PERMISSIONS.CHAT_WITH_STUDENTS,
    PERMISSIONS.CHAT_WITH_PARENTS,
    PERMISSIONS.CHAT_WITH_TEACHERS,
    PERMISSIONS.VIEW_REPORTS,
  ],

  [ROLES.CLINIC]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.VIEW_STUDENT_PROFILE,
    PERMISSIONS.VIEW_STUDENT_HEALTH,
    PERMISSIONS.EDIT_STUDENT_HEALTH,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_REPORTS,
  ],

  [ROLES.TLH]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.VIEW_STUDENT_PROFILE,
    PERMISSIONS.VIEW_TEACHERS,
    PERMISSIONS.VIEW_TEACHER_PROFILE,
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.VIEW_LESSON_PLANS,
    PERMISSIONS.EVALUATE_LESSON_PLAN,
    PERMISSIONS.VIEW_TEACHER_PERFORMANCE,
    PERMISSIONS.EVALUATE_TEACHER,
    PERMISSIONS.VIEW_TEACHER_RANKING,
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.VIEW_STUDENT_GRADES,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.ASSIGN_TASK,
  ],

  [ROLES.ANALYST]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.VIEW_TEACHERS,
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.VIEW_STUDENT_GRADES,
    PERMISSIONS.VIEW_TEACHER_PERFORMANCE,
  ],

  [ROLES.FINANCE]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_EXPENSES,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.MANAGE_PAYMENTS,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_MATERIAL_REQUESTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_REPORTS,
  ],

  [ROLES.COMMUNICATION]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.CREATE_ANNOUNCEMENT,
    PERMISSIONS.EDIT_ANNOUNCEMENT,
    PERMISSIONS.DELETE_ANNOUNCEMENT,
    PERMISSIONS.SEND_URGENT_NOTICE,
    PERMISSIONS.CREATE_GROUP_CHAT,
    PERMISSIONS.VIEW_BLOG,
    PERMISSIONS.CREATE_BLOG_POST,
    PERMISSIONS.EDIT_BLOG_POST,
    PERMISSIONS.DELETE_BLOG_POST,
    PERMISSIONS.CHAT_WITH_TEACHERS,
    PERMISSIONS.CHAT_WITH_PARENTS,
  ],

  [ROLES.HEAD_ADMIN]: [
    ...Object.values(PERMISSIONS).filter(p =>
      p !== PERMISSIONS.SYSTEM_SETTINGS &&
      p !== PERMISSIONS.MANAGE_ROLES
    ),
  ],

  [ROLES.CEO]: [
    ...Object.values(PERMISSIONS).filter(p =>
      p !== PERMISSIONS.CREATE_LEAVE_REQUEST &&
      p !== PERMISSIONS.REQUEST_MATERIALS &&
      p !== PERMISSIONS.REQUEST_PURCHASE &&
      p !== PERMISSIONS.REQUEST_DUPLICATION
    ),
  ],

  [ROLES.SUPER_ADMIN]: [
    ...Object.values(PERMISSIONS).filter(p =>
      p !== PERMISSIONS.CREATE_LEAVE_REQUEST &&
      p !== PERMISSIONS.REQUEST_MATERIALS &&
      p !== PERMISSIONS.REQUEST_PURCHASE &&
      p !== PERMISSIONS.REQUEST_DUPLICATION
    ),
  ],
};

// Helper function to check if user has permission
export const hasPermission = (userRoles, permission) => {
  if (!userRoles || userRoles.length === 0) return false;

  return userRoles.some(role => {
    const normalizedRole = typeof role === 'string' ? role.toLowerCase() : role.name?.toLowerCase();
    const rolePermissions = ROLE_PERMISSIONS[normalizedRole] || [];
    return rolePermissions.includes(permission);
  });
};

// Helper function to check if user has any of the permissions
export const hasAnyPermission = (userRoles, permissions) => {
  return permissions.some(permission => hasPermission(userRoles, permission));
};

// Helper function to check if user has all permissions
export const hasAllPermissions = (userRoles, permissions) => {
  return permissions.every(permission => hasPermission(userRoles, permission));
};

// Helper function to get user's role priority (higher number = more access)
export const getRolePriority = (role) => {
  const priorities = {
    [ROLES.SUPER_ADMIN]: 100,
    [ROLES.CEO]: 90,
    [ROLES.HEAD_ADMIN]: 80,
    [ROLES.ADMIN]: 70,
    [ROLES.HR]: 60,
    [ROLES.TLH]: 55,
    [ROLES.FINANCE]: 50,
    [ROLES.COMMUNICATION]: 45,
    [ROLES.ANALYST]: 40,
    [ROLES.COUNSELOR]: 35,
    [ROLES.CLINIC]: 30,
    [ROLES.LIBRARIAN]: 25,
    [ROLES.TEACHER]: 20,
    [ROLES.PARENT]: 10,
    [ROLES.STUDENT]: 5,
  };

  const normalizedRole = typeof role === 'string' ? role.toLowerCase() : role.name?.toLowerCase();
  return priorities[normalizedRole] || 0;
};

// Helper function to get user's highest role
export const getHighestRole = (userRoles) => {
  if (!userRoles || userRoles.length === 0) return null;

  return userRoles.reduce((highest, current) => {
    const currentPriority = getRolePriority(current);
    const highestPriority = getRolePriority(highest);
    return currentPriority > highestPriority ? current : highest;
  });
};
