# Generated by Django 5.2 on 2026-04-10 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('students', '0002_initial'),
        ('teachers', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='schedule.classscheduleslot'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='teachers.teacherassignment'),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_score',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_score',
            field=models.FloatField(default=40),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherassignment'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('exam_period', 'Exam Period'), ('event', 'Special Event'), ('teacher_training', 'Teacher Training'), ('parent_meeting', 'Parent Meeting')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_working_day', models.BooleanField(default=False, help_text='Is this a working day for teachers?')),
                ('affects_schedule', models.BooleanField(default=True, help_text='Does this event affect the regular schedule?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='users.branch')),
            ],
            options={
                'db_table': 'academic_calendar',
                'ordering': ['date'],
                'unique_together': {('branch', 'date', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_substitutions', to=settings.AUTH_USER_MODEL)),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_out', to='teachers.teacher')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitution_requests', to=settings.AUTH_USER_MODEL)),
                ('schedule_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='schedule.classscheduleslot')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_in', to='teachers.teacher')),
            ],
            options={
                'db_table': 'teacher_substitutions',
                'unique_together': {('schedule_slot', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TimetableConstraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_periods_per_day', models.PositiveIntegerField(default=8, help_text='Maximum number of periods in a day')),
                ('max_consecutive_periods', models.PositiveIntegerField(default=3, help_text='Maximum consecutive periods for a teacher')),
                ('teacher_max_periods_per_day', models.PositiveIntegerField(default=6, help_text='Maximum periods a teacher can teach per day')),
                ('teacher_max_periods_per_week', models.PositiveIntegerField(default=30, help_text='Maximum periods a teacher can teach per week')),
                ('min_break_between_periods', models.PositiveIntegerField(default=0, help_text='Minimum break required between teacher periods (in minutes)')),
                ('enforce_room_conflicts', models.BooleanField(default=True, help_text='Prevent double-booking of rooms')),
                ('enforce_teacher_conflicts', models.BooleanField(default=True, help_text='Prevent double-booking of teachers')),
                ('enforce_section_conflicts', models.BooleanField(default=True, help_text='Prevent double-booking of sections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_constraints', to='users.branch')),
            ],
            options={
                'db_table': 'timetable_constraints',
                'unique_together': {('branch',)},
            },
        ),
    ]
