# Generated by Django 5.2 on 2026-04-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_term_branch_alter_term_academic_year_alter_term_name_and_more'),
        ('schedule', '0002_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classscheduleslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classscheduleslot',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='academics.term'),
        ),
        migrations.AlterUniqueTogether(
            name='classscheduleslot',
            unique_together={('term', 'class_fk', 'section', 'day_of_week', 'period_number')},
        ),
    ]
