# Generated by Django 5.2 on 2026-04-14 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_classscheduleslot_unique_together_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(blank=True, max_length=10, null=True)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Laboratory'), ('hall', 'Hall'), ('library', 'Library'), ('other', 'Other')], default='classroom', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='users.branch')),
            ],
            options={
                'db_table': 'classrooms',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='classscheduleslot',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='schedule.classroom'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['branch', 'is_active'], name='classrooms_branch__5cdc37_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['code'], name='classrooms_code_319505_idx'),
        ),
    ]
