# Generated by Django 5.2 on 2026-04-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_exam_end_time_exam_start_time_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='custom_assignment_weight',
            field=models.FloatField(default=10, help_text='Custom weight for assignments'),
        ),
        migrations.AddField(
            model_name='exam',
            name='custom_attendance_weight',
            field=models.FloatField(default=10, help_text='Custom weight for attendance'),
        ),
        migrations.AddField(
            model_name='exam',
            name='custom_ca_weight',
            field=models.FloatField(default=20, help_text='Custom weight for continuous assessment'),
        ),
        migrations.AddField(
            model_name='exam',
            name='custom_exam_weight',
            field=models.FloatField(default=60, help_text='Custom weight for exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='weight_profile',
            field=models.CharField(choices=[('k12_standard', 'K-12 Standard (60/20/10/10)'), ('exam_heavy', 'Exam Heavy (80/10/5/5)'), ('project_based', 'Project Based (40/20/30/10)'), ('continuous', 'Continuous Assessment (30/50/10/10)'), ('exam_only', 'Exam Only (100/0/0/0)'), ('custom', 'Custom (Manual)')], default='k12_standard', help_text='Auto-applies weights when exam results are entered', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('final', 'Final'), ('mid_term', 'Mid Term'), ('unit_test', 'Unit Test'), ('diagnostic_test', 'Diagnostic Test'), ('quiz', 'Quiz'), ('homework', 'Homework'), ('project', 'Project'), ('other', 'Other')], max_length=50),
        ),
    ]
