# Generated by Django 5.2 on 2026-04-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_exam_custom_assignment_weight_and_more'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'schedule_slot')},
        ),
    ]
