# Generated by Django 5.2 on 2026-05-04 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_attendance_unique_together'),
        ('students', '0002_initial'),
        ('teachers', '0010_evaluationperiodhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='request_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterModelTable(
            name='leaverequest',
            table='leave_requests',
        ),
    ]
