# Generated by Django 5.2 on 2026-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_leaverequest_request_type_leaverequest_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
