# Generated by Django 5.2 on 2026-04-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherrating',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='teachers.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='studentelectivechoice',
            unique_together={('student', 'elective_offering')},
        ),
        migrations.AlterUniqueTogether(
            name='studentextrachoice',
            unique_together={('student', 'extra_offering')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together={('student', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherrating',
            unique_together={('parent', 'teacher', 'student')},
        ),
    ]
