# Generated by Django 5.2 on 2026-04-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
